FROM ghcr.io/lavalink-devs/lavalink:4.2.2

USER root
# RUN apt-get update && apt-get install -y python3 python3-pip curl unzip \
#     && curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp_linux -o /usr/local/bin/yt-dlp \
#     && chmod a+rx /usr/local/bin/yt-dlp \
#     && apt-get clean && rm -rf /var/lib/apt/lists/* \
#     && curl -fsSL https://deno.land/install.sh | sh \
#     && ln -s /root/.deno/bin/deno /usr/local/bin/deno
RUN mkdir -p /opt/Lavalink/plugins && chown -R lavalink:lavalink /opt/Lavalink/plugins
USER lavalink

COPY ./application.yml /opt/Lavalink/application.yml
COPY ./resources/sfx/ /opt/Lavalink/sfx/
