FROM ghcr.io/lavalink-devs/lavalink:4.2.2

USER root

RUN mkdir -p /opt/Lavalink/plugins && chown -R lavalink:lavalink /opt/Lavalink/plugins
RUN mkdir -p /opt/Lavalink/sfx && chown -R lavalink:lavalink /opt/Lavalink/sfx

USER lavalink

COPY ./application.yml /opt/Lavalink/application.yml
